typography_spectrum: 0.7343144237529486
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.8191232127137482
  lightness: 0.9773456291295588
  saturation: 0.6781400912441313
  rhythmicContrast: 0.972681493498385
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5028744270093739
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d50361ad-9504-4203-a72c-8fe3bf652d99.jpg
name: Break Free Apparel
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f279b8c5-b0ba-43ca-b83f-9eebef2b90db.jpg
purpose: []
