name: Break Free Apparel
favicon: null
layout_spectrum: 0.5095458102878183
typography_spectrum: 0.9580995792057365
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.49177162325941026
  lightness: 0.20226564188487828
  saturation: 0.9472846831195056
  rhythmicContrast: 0.7199768596328795
purpose: []
