layout_spectrum: 0.5028744270093739
typography_spectrum: 0.7343144237529486
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.8191232127137482
  lightness: 0.9773456291295588
  saturation: 0.6781400912441313
  rhythmicContrast: 0.972681493498385
name: Break Free Apparel
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
